spring.application.name=payment-service
server.port=${SERVER_PORT:8084}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mariadb://payment-db:3306/payment}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:sapassword}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

order.service.url=${ORDER_SERVICE_URL:http://order-service:8083}