services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-nodeA
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: rabbitmq-nodeA
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"

  user-service:
    build: ./user-service
    container_name: user-service-nodeA
    environment:
      DATABASE_URL: ${DATABASE_URL_USER}
      JWT_SECRET: ${JWT_SECRET}
      PORT: 8001
    ports:
      - "8001:8001"
    depends_on:
      - postgres

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway-nodeA
    environment:
      PORT: 8000
      JWT_SECRET: ${JWT_SECRET}
      USER_SERVICE_URL: ${USER_SERVICE_URL}
      MOVIE_SERVICE_URL: ${MOVIE_SERVICE_URL}
      BOOKING_SERVICE_URL: ${BOOKING_SERVICE_URL}
      PAYMENT_SERVICE_URL: ${PAYMENT_SERVICE_URL}
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      target: development
    container_name: frontend-nodeA
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      VITE_PORT: 3000
    command: npm run dev

volumes:
  postgres_data:
